name = "embedding-app"
main = "worker.ts"
compatibility_date = "2024-02-26"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "markdown-vectors"
remote = true

[assets]
directory = "frontend/out"
binding = "ASSETS"
