name = "embedding-app"
main = "worker.js"
compatibility_date = "2024-02-26"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "markdown-vectors"
remote = true

[dev]
port = 3000
ip = "0.0.0.0"
